version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001" # Expose backend on port 3001
    env_file:
      - ./backend/.env # Reference the backend environment variables
    command: sh -c "until nc -z -v -w30 mysql 3306; do echo 'Waiting for MySQL...'; sleep 1; done && node server.js"
    depends_on:
      - mysql
    networks:
      - dream-vacation-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile # Using the custom Dockerfile with NGINX
    env_file:
      - ./frontend/.env
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - dream-vacation-network

  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306" # Expose MySQL on port 3306
    env_file:
      - ./backend/.env # Database-specific environment variables
    volumes:
      - db_data:/var/lib/mysql # Persist database data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql # Mount init.sql script to initialize database
    networks:
      - dream-vacation-network

volumes:
  db_data:

networks:
  dream-vacation-network:
    driver: bridge
