name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Get Git commit SHA
        id: git_sha
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push backend Docker image
        run: |
          docker build -t bufic/dream-vacation-app:backend-$GIT_SHA -t bufic/dream-vacation-app:backend-latest -f Dream-Vacation-App-main/backend/Dockerfile Dream-Vacation-App-main/backend
          docker push bufic/dream-vacation-app:backend-$GIT_SHA
          docker push bufic/dream-vacation-app:backend-latest

      - name: Build and push frontend Docker image
        run: |
          docker build -t bufic/dream-vacation-app:frontend-$GIT_SHA -t bufic/dream-vacation-app:frontend-latest -f Dream-Vacation-App-main/frontend/Dockerfile Dream-Vacation-App-main/frontend
          docker push bufic/dream-vacation-app:frontend-$GIT_SHA
          docker push bufic/dream-vacation-app:frontend-latest
