name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push frontend Docker image
        run: |
          docker build -t bufic/dream-vacation-app-frontend:frontendv1 -f Dream-vacation-app/frontend/Dockerfile Dream-vacation-app/frontend
          docker push bufic/dream-vacation-app-frontend:frontendv1

      - name: Build and push backend Docker image
        run: |
          docker build -t bufic/dream-vacation-app-backend:backendv1 -f Dream-vacation-app/backend/Dockerfile Dream-vacation-app/backend
          docker push bufic/dream-vacation-app-backend:backendv1
